filter:
  #The headers filtered out by engine, that do not usually contain correlations.
  headers: ["Expires", "X-FRAME-OPTIONS", "Content-type", "Content-Encoding", "Host", "Content-Length", "Accept-Encoding", "Upgrade-Insecure-Requests", "Origin",
            "Accept", "Date", "Server", "X-Powered-By", "X-Application-Context", "Cache-control", "Proxy-Connection", "Connection", "Pragma", "Last-Modified", "Age", "User-Agent",
            "Accept-Language", "Accept-Ranges", "ETag", "Vary", "Set-Cookie", "Transfer-Encoding", "X-Requested-With", "Strict-Transport-Security", "X-XSS-Protection", "X-CONTENT-TYPE-OPTIONS", "X-CDN"]

  #The extensions filtered out by engine, that do not usually contain correlations.
  extensions: ['.ico', '.jpeg', '.jpg', '.gif']

  #The non-text content type filtered out by engine, that do not usually contain correlations.
  contentType: ['image/jpg', 'font/woff', 'text/css', 'image/png', 'video/mp4', 'image/x-icon', 'image/jpeg']

  #The HTML tags (for example, `font`) filtered out by engine, that do not usually contain correlations.
  htmlTags: ['font', 'style', 'br', 'link', 'img']

  #The HTML attributes (for example, `id`) filtered out by engine, that do not usually contain correlations.
  htmlAttributes: ['size', 'color', 'bgcolor', 'type', 'name', 'readonly', 'disabled', 'maxlength', 'autocomplete', 'formaction', 'id', 'style']

rankers:
  knownWordsRanker:
    isEnabled: true
    certainty:
      correlationCertainty: 0
      nonCorrelationCertainty: 0.8
    patterns: #These patterns will be used to filter out values suspected as correlations
      fileName: !!str ^[.\w](?:[\w._-]*[\w])?\.[\w~!]{1,5}$
      path: !!str ^(((\\\\|/)([\w]+(\\|/|\.[\w]+))+)|(([\w]+)((\\|/)[\w]*)+(\.[\w]+)?))$
      url: !!str ^(\w+:\/\/|/)?(w{3}\.)?\w+([\-.][a-z0-9]+)*\.[a-z]{2,5}(:[0-9]{1,5})?(\/.*)?$
      email: !!str ^(([^<>()\[\]\\.,;:\s@\"]+(\.[^<>()\[\]\\.,;:\s@\"]+)*)|(\".+\"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$
      RFC3339Date: !!str ^([0-9]+)-(0[1-9]|1[012])-(0[1-9]|[12][0-9]|3[01])[Tt\s]([01][0-9]|2[0-3]):([0-5][0-9]):([0-5][0-9]|60)(\.[0-9]+)?(([Zz])|([\+|\-]([01][0-9]|2[0-3]):[0-5][0-9]))$
      number: !!str ^\d+$
  englishLettersRanker:
    isEnabled: true
    certainty:
      correlationCertainty: 0.3
      nonCorrelationCertainty: 0.9
  characterVarietyRanker:
    isEnabled: true
    certainty:
      correlationCertainty: 1.5
      nonCorrelationCertainty: 0.01