name: devWeb
version: 2021.0.0

measurements:                       #Configuration for storing measurements
  adapters: ["influxDB"]              #Configuration for database adapters that is used for measurements. Available adapters are [sqlite, influxDB, influxDBV2].
  useProxy: false                   #Indicates whether to use proxy settings from rts.yml during connection to measurements instance

influxDB:                           #Configuration for InfluxDB adapter instance
  url: "http://nimbusserver:8186"                           #The InfluxDB endpoint (for example: http://myHost:8086)
  dbName: "LRD"                #The InfluxDB v1 database name