measurements:                       #Configuration for storing measurements
  useSqliteDB: false                 #If true, all measurements is stored in local SQLite database
  useInfluxDB: true                #If true, all measurements is send to InfluxDB instance
  useProxyForInfluxDB: false        #Indicates whether to use proxy settings from rts.yml during connection to InfluxDB instance
  influxDBURL: "http://localhost:8087?db=devwebdemo"                   #InfluxDB endpoint and database name (for example: http://myHost:8086?db=devWebDB)