parameters:                     #The parameters header, it must be the first line of the file
  - name: user              #The name of the parameter that can later be used in the code
    type: csv                   #The type of the data source of the parameter. The valid values are: csv 
    fileName: insco.csv         #The name of the file that has all the values for this parameter
    columnName: username             #The column name used to draw values for this parameter
    nextValue: iteration        #The logic used to know when to retrieve new values
    nextRow: sequential         #The logic used to know how to retrieve new values
    onEnd: loop                 #What happens when there are no more values remaining and the script needs another value
  - name: password              #Another parameter...
    type: csv
    fileName: insco.csv
    columnName: password
    nextValue: iteration
    nextRow: same as user
    onEnd: loop